# Observium and MariaDB container
# Maintained by Eugene Letenkov <letenkov@mandarin.solutions>

version: '3.3'

services:

    db:
       image: mariadb:latest
       container_name: observium_db
       environment:
         - MYSQL_ROOT_PASSWORD=passw0rd
         - MYSQL_USER=observium
         - MYSQL_PASSWORD=passw0rd
         - MYSQL_DATABASE=observium
         - TZ=Europe/Moscow
       volumes:
         - /srv/docker/observium/data:/var/lib/mysql
       networks:
         - backend
       restart: always

    app:
       image: mandarinsolutions/observium
       container_name: observium_app
       environment:
         - OBSERVIUM_ADMIN_USER=admin
         - OBSERVIUM_ADMIN_PASS=passw0rd
         - OBSERVIUM_DB_HOST=observiumdb
         - OBSERVIUM_DB_NAME=observium
         - OBSERVIUM_DB_USER=observium 
         - OBSERVIUM_DB_PASS=passw0rd
         - TZ=Europe/Moscow
       volumes:
         - /srv/docker/observium/logs:/opt/observium/logs
         - /srv/docker/observium/lock:/opt/observium/lock
         - /srv/docker/observium/rrd:/opt/observium/rrd
       networks:
         - frontend
         - backend
       restart: always
       depends_on:
         - db
       extra_hosts:
         - observium:92.53.69.56
         - vpn1:95.213.138.82
         - vpn2:95.213.138.83
         - npp1:95.213.138.89
         - nx1:95.213.138.90
         - sp1:95.213.138.91
         - wspcm1:95.213.138.92
         - wspcm:95.213.138.92
         - dm1:95.213.138.93
         - css1:95.213.138.94
         - cs41134:95.213.138.85
         - cs41565:95.213.138.86
         - lb1:92.53.69.240
         - lb2:92.53.69.240

networks:
    frontend:
       external:
          name: frontend
    backend:
       external:
          name: observium_backend
      
