# Observium and MariaDB container
# Maintained by letenkov@madarin.solutions

version: '3.3'

services:

  observiumdb:
       image: mariadb:latest
       environment:
         - MYSQL_ROOT_PASSWORD=passw0rd
         - MYSQL_USER=observium
         - MYSQL_PASSWORD=passw0rd
         - MYSQL_DATABASE=observium
         - TZ=Europe/Moscow
       volumes:
         - /srv/docker/observium/data:/var/lib/mysql
#         - /srv/docker/observium/mysql:/docker-entrypoint-initdb.d
       networks:
         - back-tier
       restart: always

  observiumap:
       image: mandarinsolutions/observium
       environment:
         - OBSERVIUM_ADMIN_USER=admin
         - OBSERVIUM_ADMIN_PASS=passw0rd
         - OBSERVIUM_DB_HOST=observiumdb
         - OBSERVIUM_DB_NAME=observium
         - OBSERVIUM_DB_USER=observium 
         - OBSERVIUM_DB_PASS=passw0rd
         - TZ=Europe/Moscow
       volumes:
         - /srv/docker/observium/logs:/opt/observium/logs
         - /srv/docker/observium/lock:/opt/observium/lock
         - /srv/docker/observium/rrd:/opt/observium/rrd
       networks:
         - front-tier
         - back-tier
       restart: always
       depends_on:
         - observiumdb
       extra_hosts:
         - observium:92.53.69.56
         - vpn1:95.213.138.82
         - vpn2:95.213.138.83
         - npp1:95.213.138.89
         - nx1:95.213.138.90
         - sp1:95.213.138.91
         - wsp1:95.213.138.92
         - dm1:95.213.138.93
         - css1:95.213.138.94
         - cs41134:95.213.138.85
         - cs41565:95.213.138.86

  observiumgw:
       image: mandarinsolutions/caddy:${CADDY_VERSION:-0.10.9}
       ports:
         - 80:80
         - 443:443
         - 9180:9180
       volumes:
         - certs:/.caddy
       networks:
         - front-tier
       healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:80"]
         interval: 5s
         timeout: 1s
         retries: 3

volumes:
  certs: {}

networks:
  front-tier:
      driver: bridge
  back-tier:
      driver: bridge

